### ISSUE TITLE
CASIA-B Dataset Request

### ISSUE THREAD

**Issue by ZhengLeon** [Jaychoukobbe/GaitPart#1]
Hi,@Jaychoukobbe 
Thanks for your great job, the link of CASIA-B dataset is not available now. If you have the data saved? I just wanna use the dataset for research. 
Thanks!

**Comment by OliverHxh** [comment]
@ZhengLeon try this: http://www.cbsr.ia.ac.cn/GaitDatasetB-silh.zip, but this only provides silhouettes images.

**Comment by ZhengLeon** [comment]
@Jaychoukobbe 
Thanks a lot, the link now is work!
