### ISSUE TITLE
UserWarning: seq:005-bg-01-162, frame:005-bg-01-162-044.png, no data, 0.

### ISSUE THREAD

**Issue by Adrian6N** [Jaychoukobbe/GaitPart#11]
Hello, when i start pretreatment.py,  i receive these this warning : UserWarning: seq:005-bg-01-162, frame:005-bg-01-162-044.png, no data, 0. Do you now the possible cause of this?
And also this warning "UserWarning: seq:005-bg-01-162, frame:005-bg-01-162-034.png, no center."

**Comment by small-code-cat** [comment]
> Hello, when i start pretreatment.py, i receive these this warning : UserWarning: seq:005-bg-01-162, frame:005-bg-01-162-044.png, no data, 0. Do you now the possible cause of this? And also this warning "UserWarning: seq:005-bg-01-162, frame:005-bg-01-162-034.png, no center."

Hello, I also encountered this problem. How did you solve it？

**Comment by small-code-cat** [comment]
> > Hello, when i start pretreatment.py, i receive these this warning : UserWarning: seq:005-bg-01-162, frame:005-bg-01-162-044.png, no data, 0. Do you now the possible cause of this? And also this warning "UserWarning: seq:005-bg-01-162, frame:005-bg-01-162-034.png, no center."
> 
> Hello, I also encountered this problem. How did you solve it？

I found the reason. It was scisc.imsave that reported an error. Change it to imageio.imsave
