### ISSUE TITLE
您好，请问测试的时候，是输入一个人的一个视频，还是输入一个人的多个视频？？

### ISSUE THREAD

**Issue by super-handsome-kang** [Jaychoukobbe/GaitPart#2]

**Comment by OliverHxh** [comment]
probe和gallery中都会包含同一个人不重复的多段视频。

**Comment by super-handsome-kang** [comment]
好的非常感谢，还有个问题想问一下，就是训练的时候是每个视频随机抽取30帧图像，那么测试的时候是如何抽取帧图像的呢？是像训练的时候一样一个视频抽取30帧还是把一个视频的所有帧都输入进模型？

**Comment by OliverHxh** [comment]
@super-handsome-kang 你好，测试时输入全部帧。

**Comment by super-handsome-kang** [comment]
好的，谢谢！！
