### ISSUE TITLE
self.bin_num = [16]

### ISSUE THREAD

**Issue by mapei319** [Jaychoukobbe/GaitPart#5]
您好，打扰了，self.bin_num = [16]，请问这块的值怎么不是多个尺度的，仅是S=5?

**Comment by OliverHxh** [comment]
论文里就是这么写的

**Comment by weilanhanf** [comment]
> 您好，打扰了，self.bin_num = [16]，请问这块的值怎么不是多个尺度的，仅是S=5?

请问这个16指的是将一个silhouette轮廓横向分成16份吗，代码中的config设置的batch_size=(8, 16)，8是指8个silhouette，每个16份吗，
