### ISSUE TITLE
I downloaded and ran your code, but the final experimental result is lower than yours.

### ISSUE THREAD

**Issue by XiaoBingCQY** [Jaychoukobbe/GaitPart#7]
Sorry,I downloaded and ran your code, but the final experimental result is lower than yours. Do I need to adjust some parameters? Hope to get your help.

**Comment by OliverHxh** [comment]
You can try to train the network with more iterations, and check the results in different checkpoints.

**Comment by zhang123-sys** [comment]
> You can try to train the network with more iterations, and check the results in different checkpoints.

![image](https://user-images.githubusercontent.com/63956071/191507507-e34898d1-19aa-4925-a9f7-4a7eba8136bf.png)
Excuse me, when I train
RuntimeError: shape '[3840, 32, 4, -1, 2]' is invalid for input of size 491520
