### ISSUE TITLE
Some details questions

### ISSUE THREAD

**Issue by Nathanyaowu** [Jaychoukobbe/GaitPart#8]
Hello , i am very appreciate you rewrite the gait part code. And i am stuck by a question at the MTB module. Accroding to gaitpart's paper the MTB module don't plus the x_in in the final result.
here is your code:
![image](https://user-images.githubusercontent.com/36793475/128313610-776730d2-e9e8-42ab-b75e-bf2128cc4717.png)
Below is the ideal code i think :
![image](https://user-images.githubusercontent.com/36793475/128313717-34a84ae5-2770-4678-9973-b1baf9b330bd.png)
But i just wonder that does this normal compute and the residual compute will affect the final result? Becasue i also using your code to train the network on the CASIA-B dataset. The result is just about 1 percent gap compared to gaitpart's paper.
Looking for your reply. Thanks in advance.

**Comment by OliverHxh** [comment]
I do think this residual connection may affect the accuracy. And do you have the results that not includes the  residual connection?

**Comment by Nathanyaowu** [comment]
Yep, after your reply i delete the x_in in the MTB module, and retrain the network with the same config. Here is my test result, they all train on CASIA-B, 73 for training, 51 for testing ,12000 iters.
MTB with  resudial part:
![GaitPart](https://user-images.githubusercontent.com/36793475/128794285-14a5eca4-ec2b-46e7-935e-ac679cb3750c.png)
 MTB without  resudial part:
![gaitpart1without1residual](https://user-images.githubusercontent.com/36793475/128794818-612bff02-aab6-4910-99be-f58ea6841166.png)

According to the test result , the model get some improve in the CL part indeed.But the BG and NM lose little accuracy.

**Comment by Nathanyaowu** [comment]
Typo: 74 for training(exclude the 5 subject) ,50 for test
